version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src" # Need to specify the sub-directory to make sure projects are picked up
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
