name: Create versioning pull request

on:
  # push:
  #   branches: ["main"]
  #   tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  create_version_pull_request:
    name: Create versioning pull request
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all tags

      - name: Download auto
        run: |
          curl -kL -o - https://github.com/intuit/auto/releases/download/v11.3.0/auto-linux.gz | gunzip > ${{ runner.temp }}/auto
          chmod +x ${{ runner.temp }}/auto

      - name: Get next release number
        id: next_release
        run: ${{ runner.temp }}/auto shipit --dry-run --quiet --base-branch ${{ github.ref_name}}

      - name: Update changelog
        run: ${{ runner.temp }}/auto changelog --name github-actions[bot] --email github-actions[bot]@users.noreply.github.com

      - name: Create versioning pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: auto/release
          title: Release version
          commit-message: Release version
