name: Docs only (PR)

on:
  pull_request:
    branches: ["main"]
    paths:
      - "!**" # Exclude every file
      - "README.md" # Except only readme changes
      - "CHANGELOG.md" # And changelog changes
      - ".github/workflows/copilot-setup-steps.yml"

jobs:
  pr_complete:
    name: PR checks complete
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR required checks complete"
